### ISSUE TITLE
Maybe add this Stanford course cs20si (2017)

### ISSUE THREAD

**Issue by DanielBeckstein** [jtoy/awesome-tensorflow#102]
## CS20 SI: TensorFlow for DeepLearning Research

Syllabus  http://web.stanford.edu/class/cs20si/syllabus.html

Contains slides + notes + assignment code, but no video unfortunately.

Examples :
- slide  http://web.stanford.edu/class/cs20si/lectures/slides_09.pdf
- note  http://web.stanford.edu/class/cs20si/lectures/notes_09.pdf
- code  https://github.com/chiphuyen/tf-stanford-tutorials/tree/master/assignments/style_transfer

**Comment by jtoy** [comment]
great, want to add it as a pull request?
