### ISSUE TITLE
Adding Tensorflow User Group Slack channel

### ISSUE THREAD

**Issue by yapjiaqing** [jtoy/awesome-tensorflow#113]
Here's the invite link to the global Tensorflow User Group Slack channel (tensorflow-user-group.slack.com): https://join.slack.com/t/tensorflow-user-group/shared_invite/MjE5MzM5ODUxMDI3LTE1MDEzMDcyODItYTU3MzBjZmJjNw

**Comment by Mazecreator** [comment]
This link doesn't seem valid
