### ISSUE TITLE
Pre-trained tensorflow weights?

### ISSUE THREAD

**Issue by pavelgonchar** [jtoy/awesome-tensorflow#23]
Hi,

What about Tensorflow Model Zoo (similar to Caffe Model Zoo)? 
I would like to contribute with converted VGG Face weights https://github.com/pavelgonchar/vgg-face-tensorflow

Also please check out https://github.com/tensorflow/tensorflow/issues/6

Thanks,
Pavel

**Comment by jtoy** [comment]
love it, lets get them added in here
