### ISSUE TITLE
Add Deep Learning (Adaptive Computation and Machine Learning series) Hardcover

### ISSUE THREAD

**Issue by Mazecreator** [jtoy/awesome-tensorflow#75]
This book should be added:

Deep Learning (Adaptive Computation and Machine Learning series) Hardcover – November 18, 2016
by Ian Goodfellow  (Author), Yoshua Bengio  (Author), Aaron Courville  (Author)

This is a great read, very helpful!

Can be found on Amazon.

**Comment by jtoy** [comment]
is it tensorflow? doesnt seem to be

**Comment by Mazecreator** [comment]
Sorry, you are right, it really isn't TensorFlow specific.

Great book though!
